### ISSUE TITLE
Update for ECO mode?

### ISSUE THREAD

**Issue by cmeans** [smartthings-users/device-type.nest#39]
NEST has modified their configuration a bit, and they've added an ECO mode, which doesn't appear to be quite the same as AWAY.  Before I had routines that would set the NEST to AWAY if my electricity costs crossed a specific threshold, but now I need it to set the NEST to ECO mode, which isn't currently an option.

Any chance you could provide an update for these new features?

**Comment by lowdrag** [comment]
Hi I'd like to know when the change was made and if possibly details of the
change because I think it may have affected me because now my thermostat
won't shut off it keeps running and raises the temperature did like almost
100° and they're telling me that I have to pay a technician to change my
wiring in the house but I don't see why if it was working for like eight
months this would happen. They are telling me my first must've changed or
something happened because of aging or something but that's crazy the
furnace has been running for probably well over 15 years in the same
fashion and never has anything been altered. So I believe it's a change
they made and that I am not going to pay more money every time the update
to change something on my end with my furnace

**Comment by cmeans** [comment]
Sorry, I don't have that level of detail...I certainly didn't experience any problems because of it, only lost some of the functionality I had before.  I've since uninstalled this Device Type and moved onto tonesto7/nest-manager.  It's not perfect, but at least recognizes the modes supported by the NEST, as well as integration for NEST Protect etc.  My routines can now switch into ECO mode, but switching back to AUTO is still a bit problematic.
